import { faker } from '@faker-js/faker';

type ICountry = {
  id?: string;
  name: string;
  iso2: string;
  iso3: string;
  isoNumeric: string;
  phoneCode: string;
  continent: string;
  capital: string;
  timeZone: string;
  currency: string;
  status?: boolean;
  wholePart?: string;
  languageCodes: string;
};

const countries: ICountry[] = [
  {
    name: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    isoNumeric: '4',
    phoneCode: '93',
    continent: 'Asia',
    capital: 'Kabul',
    timeZone: 'Asia/Kabul',
    currency: 'Afghani',
    languageCodes: 'fa-AF,ps,uz-AF,tk',
  },
  {
    name: 'Albania',
    iso2: 'AL',
    iso3: 'ALB',
    isoNumeric: '8',
    phoneCode: '355',
    continent: 'Europe',
    capital: 'Tirana',
    timeZone: 'Europe/Tirane',
    currency: 'Lek',
    languageCodes: 'sq,el',
  },
  {
    name: 'Algeria',
    iso2: 'DZ',
    iso3: 'DZA',
    isoNumeric: '12',
    phoneCode: '213',
    continent: 'Africa',
    capital: 'Algiers',
    timeZone: 'Africa/Algiers',
    currency: 'Dinar',
    languageCodes: 'ar-DZ',
  },
  {
    name: 'American Samoa',
    iso2: 'AS',
    iso3: 'ASM',
    isoNumeric: '16',
    phoneCode: '1-684',
    continent: 'Oceania',
    capital: 'Pago Pago',
    timeZone: 'Pacific/Pago_Pago',
    currency: 'Dollar',
    languageCodes: 'en-AS,sm,to',
  },
  {
    name: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    isoNumeric: '20',
    phoneCode: '376',
    continent: 'Europe',
    capital: 'Andorra la Vella',
    timeZone: 'Europe/Andorra',
    currency: 'Euro',
    languageCodes: 'ca',
  },
  {
    name: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
    isoNumeric: '24',
    phoneCode: '244',
    continent: 'Africa',
    capital: 'Luanda',
    timeZone: 'Africa/Lagos',
    currency: 'Kwanza',
    languageCodes: 'pt-AO',
  },
  {
    name: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
    isoNumeric: '660',
    phoneCode: '1-264',
    continent: 'North America',
    capital: 'The Valley',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-AI',
  },
  {
    name: 'Antarctica',
    iso2: 'AQ',
    iso3: 'ATA',
    isoNumeric: '10',
    phoneCode: '672',
    continent: 'Antarctica',
    capital: '',
    timeZone: 'Antarctica/Troll',
    currency: 'Troll',
    languageCodes: '',
  },
  {
    name: 'Antigua and Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    isoNumeric: '28',
    phoneCode: '1-268',
    continent: 'North America',
    capital: "St. John's",
    timeZone: 'America/Antigua',
    currency: 'Dollar',
    languageCodes: 'en-AG',
  },
  {
    name: 'Argentina',
    iso2: 'AR',
    iso3: 'ARG',
    isoNumeric: '32',
    phoneCode: '54',
    continent: 'South America',
    capital: 'Buenos Aires',
    timeZone: 'America/Argentina/Buenos_Aires',
    currency: 'Peso',
    languageCodes: 'es-AR,en,it,de,fr,gn',
  },
  {
    name: 'Armenia',
    iso2: 'AM',
    iso3: 'ARM',
    isoNumeric: '51',
    phoneCode: '374',
    continent: 'Asia',
    capital: 'Yerevan',
    timeZone: 'Asia/Yerevan',
    currency: 'Dram',
    languageCodes: 'hy',
  },
  {
    name: 'Aruba',
    iso2: 'AW',
    iso3: 'ABW',
    isoNumeric: '533',
    phoneCode: '297',
    continent: 'North America',
    capital: 'Oranjestad',
    timeZone: 'America/Curacao',
    currency: 'Guilder',
    languageCodes: 'nl-AW,es,en',
  },
  {
    name: 'Australia',
    iso2: 'AU',
    iso3: 'AUS',
    isoNumeric: '36',
    phoneCode: '61',
    continent: 'Oceania',
    capital: 'Canberra',
    timeZone: 'Australia/Sydney',
    currency: 'Dollar',
    languageCodes: 'en-AU',
  },
  {
    name: 'Austria',
    iso2: 'AT',
    iso3: 'AUT',
    isoNumeric: '40',
    phoneCode: '43',
    continent: 'Europe',
    capital: 'Vienna',
    timeZone: 'Europe/Vienna',
    currency: 'Euro',
    languageCodes: 'de-AT,hr,hu,sl',
  },
  {
    name: 'Azerbaijan',
    iso2: 'AZ',
    iso3: 'AZE',
    isoNumeric: '31',
    phoneCode: '994',
    continent: 'Asia',
    capital: 'Baku',
    timeZone: 'Asia/Baku',
    currency: 'Manat',
    languageCodes: 'az,ru,hy',
  },
  {
    name: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    isoNumeric: '44',
    phoneCode: '1-242',
    continent: 'North America',
    capital: 'Nassau',
    timeZone: 'America/Nassau',
    currency: 'Dollar',
    languageCodes: 'en-BS',
  },
  {
    name: 'Bahrain',
    iso2: 'BH',
    iso3: 'BHR',
    isoNumeric: '48',
    phoneCode: '973',
    continent: 'Asia',
    capital: 'Manama',
    timeZone: 'Asia/Bahrain',
    currency: 'Dinar',
    languageCodes: 'ar-BH,en,fa,ur',
  },
  {
    name: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    isoNumeric: '50',
    phoneCode: '880',
    continent: 'Asia',
    capital: 'Dhaka',
    timeZone: 'Asia/Dhaka',
    currency: 'Taka',
    languageCodes: 'bn-BD,en',
  },
  {
    name: 'Barbados',
    iso2: 'BB',
    iso3: 'BRB',
    isoNumeric: '52',
    phoneCode: '1-246',
    continent: 'North America',
    capital: 'Bridgetown',
    timeZone: 'America/Barbados',
    currency: 'Dollar',
    languageCodes: 'en-BB',
  },
  {
    name: 'Belarus',
    iso2: 'BY',
    iso3: 'BLR',
    isoNumeric: '112',
    phoneCode: '375',
    continent: 'Europe',
    capital: 'Minsk',
    timeZone: 'Europe/Minsk',
    currency: 'Ruble',
    languageCodes: 'be,ru',
  },
  {
    name: 'Belgium',
    iso2: 'BE',
    iso3: 'BEL',
    isoNumeric: '56',
    phoneCode: '32',
    continent: 'Europe',
    capital: 'Brussels',
    timeZone: 'Europe/Brussels',
    currency: 'Euro',
    languageCodes: 'nl-BE,fr-BE,de-BE',
  },
  {
    name: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    isoNumeric: '84',
    phoneCode: '501',
    continent: 'North America',
    capital: 'Belmopan',
    timeZone: 'America/Belize',
    currency: 'Dollar',
    languageCodes: 'en-BZ,es',
  },
  {
    name: 'Benin',
    iso2: 'BJ',
    iso3: 'BEN',
    isoNumeric: '204',
    phoneCode: '229',
    continent: 'Africa',
    capital: 'Porto-Novo',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-BJ',
  },
  {
    name: 'Bermuda',
    iso2: 'BM',
    iso3: 'BMU',
    isoNumeric: '60',
    phoneCode: '1-441',
    continent: 'North America',
    capital: 'Hamilton',
    timeZone: 'Atlantic/Bermuda',
    currency: 'Dollar',
    languageCodes: 'en-BM,pt',
  },
  {
    name: 'Bhutan',
    iso2: 'BT',
    iso3: 'BTN',
    isoNumeric: '64',
    phoneCode: '975',
    continent: 'Asia',
    capital: 'Thimphu',
    timeZone: 'Asia/Thimphu',
    currency: 'Ngultrum',
    languageCodes: 'dz',
  },
  {
    name: 'Bolivia',
    iso2: 'BO',
    iso3: 'BOL',
    isoNumeric: '68',
    phoneCode: '591',
    continent: 'South America',
    capital: 'Sucre',
    timeZone: 'America/La_Paz',
    currency: 'Boliviano',
    languageCodes: 'es-BO,qu,ay',
  },
  {
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    isoNumeric: '70',
    phoneCode: '387',
    continent: 'Europe',
    capital: 'Sarajevo',
    timeZone: 'Europe/Belgrade',
    currency: 'Marka',
    languageCodes: 'bs,hr-BA,sr-BA',
  },
  {
    name: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
    isoNumeric: '72',
    phoneCode: '267',
    continent: 'Africa',
    capital: 'Gaborone',
    timeZone: 'Africa/Maputo',
    currency: 'Pula',
    languageCodes: 'en-BW,tn-BW',
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    iso3: 'BRA',
    isoNumeric: '76',
    phoneCode: '55',
    continent: 'South America',
    capital: 'Brasilia',
    timeZone: 'America/Sao_Paulo',
    currency: 'Real',
    languageCodes: 'pt-BR,es,en,fr',
  },
  {
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    iso3: 'IOT',
    isoNumeric: '86',
    phoneCode: '246',
    continent: 'Asia',
    capital: 'Diego Garcia',
    timeZone: 'Indian/Chagos',
    currency: 'Dollar',
    languageCodes: 'en-IO',
  },
  {
    name: 'British Virgin Islands',
    iso2: 'VG',
    iso3: 'VGB',
    isoNumeric: '92',
    phoneCode: '1-284',
    continent: 'North America',
    capital: 'Road Town',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-VG',
  },
  {
    name: 'Brunei',
    iso2: 'BN',
    iso3: 'BRN',
    isoNumeric: '96',
    phoneCode: '673',
    continent: 'Asia',
    capital: 'Bandar Seri Begawan',
    timeZone: 'Asia/Brunei',
    currency: 'Dollar',
    languageCodes: 'ms-BN,en-BN',
  },
  {
    name: 'Bulgaria',
    iso2: 'BG',
    iso3: 'BGR',
    isoNumeric: '100',
    phoneCode: '359',
    continent: 'Europe',
    capital: 'Sofia',
    timeZone: 'Europe/Sofia',
    currency: 'Lev',
    languageCodes: 'bg,tr-BG',
  },
  {
    name: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    isoNumeric: '854',
    phoneCode: '226',
    continent: 'Africa',
    capital: 'Ouagadougou',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-BF',
  },
  {
    name: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
    isoNumeric: '108',
    phoneCode: '257',
    continent: 'Africa',
    capital: 'Bujumbura',
    timeZone: 'Africa/Maputo',
    currency: 'Franc',
    languageCodes: 'fr-BI,rn',
  },
  {
    name: 'Cambodia',
    iso2: 'KH',
    iso3: 'KHM',
    isoNumeric: '116',
    phoneCode: '855',
    continent: 'Asia',
    capital: 'Phnom Penh',
    timeZone: 'Asia/Phnom_Penh',
    currency: 'DolRielslar',
    languageCodes: 'km,fr,en',
  },
  {
    name: 'Cameroon',
    iso2: 'CM',
    iso3: 'CMR',
    isoNumeric: '120',
    phoneCode: '237',
    continent: 'Africa',
    capital: 'Yaounde',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'en-CM,fr-CM',
  },
  {
    name: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    isoNumeric: '124',
    phoneCode: '1',
    continent: 'North America',
    capital: 'Ottawa',
    timeZone: 'America/Toronto',
    currency: 'Dollar',
    languageCodes: 'en-CA,fr-CA,iu',
  },
  {
    name: 'Cape Verde',
    iso2: 'CV',
    iso3: 'CPV',
    isoNumeric: '132',
    phoneCode: '238',
    continent: 'Africa',
    capital: 'Praia',
    timeZone: 'Atlantic/Cape_Verde',
    currency: 'Escudo',
    languageCodes: 'pt-CV',
  },
  {
    name: 'Cayman Islands',
    iso2: 'KY',
    iso3: 'CYM',
    isoNumeric: '136',
    phoneCode: '1-345',
    continent: 'North America',
    capital: 'George Town',
    timeZone: 'America/Cayman',
    currency: 'Dollar',
    languageCodes: 'en-KY',
  },
  {
    name: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
    isoNumeric: '140',
    phoneCode: '236',
    continent: 'Africa',
    capital: 'Bangui',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-CF,sg,ln,kg',
  },
  {
    name: 'Chad',
    iso2: 'TD',
    iso3: 'TCD',
    isoNumeric: '148',
    phoneCode: '235',
    continent: 'Africa',
    capital: "N'Djamena",
    timeZone: 'Africa/Ndjamena',
    currency: 'Franc',
    languageCodes: 'fr-TD,ar-TD,sre',
  },
  {
    name: 'Chile',
    iso2: 'CL',
    iso3: 'CHL',
    isoNumeric: '152',
    phoneCode: '56',
    continent: 'South America',
    capital: 'Santiago',
    timeZone: 'America/Santiago',
    currency: 'Peso',
    languageCodes: 'es-CL',
  },
  {
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    isoNumeric: '156',
    phoneCode: '86',
    continent: 'Asia',
    capital: 'Beijing',
    timeZone: 'Asia/Shanghai',
    currency: 'Renminbi',
    wholePart: 'Yuan',
    languageCodes: 'zh-CN,yue,wuu,dta,ug,za',
  },
  {
    name: 'Christmas Island',
    iso2: 'CX',
    iso3: 'CXR',
    isoNumeric: '162',
    phoneCode: '61',
    continent: 'Asia',
    capital: 'Flying Fish Cove',
    timeZone: 'Indian/Christmas',
    currency: 'Dollar',
    languageCodes: 'en,zh,ms-CC',
  },
  {
    name: 'Cocos Islands',
    iso2: 'CC',
    iso3: 'CCK',
    isoNumeric: '166',
    phoneCode: '61',
    continent: 'Asia',
    capital: 'West Island',
    timeZone: 'Indian/Cocos',
    currency: 'Dollar',
    languageCodes: 'ms-CC,en',
  },
  {
    name: 'Colombia',
    iso2: 'CO',
    iso3: 'COL',
    isoNumeric: '170',
    phoneCode: '57',
    continent: 'South America',
    capital: 'Bogota',
    timeZone: 'America/Bogota',
    currency: 'Peso',
    languageCodes: 'es-CO',
  },
  {
    name: 'Comoros',
    iso2: 'KM',
    iso3: 'COM',
    isoNumeric: '174',
    phoneCode: '269',
    continent: 'Africa',
    capital: 'Moroni',
    timeZone: 'Indian/Comoro',
    currency: 'Franc',
    languageCodes: 'ar,fr-KM',
  },
  {
    name: 'Cook Islands',
    iso2: 'CK',
    iso3: 'COK',
    isoNumeric: '184',
    phoneCode: '682',
    continent: 'Oceania',
    capital: 'Avarua',
    timeZone: 'Pacific/Rarotonga',
    currency: 'Dollar',
    languageCodes: 'en-CK,mi',
  },
  {
    name: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    isoNumeric: '188',
    phoneCode: '506',
    continent: 'North America',
    capital: 'San Jose',
    timeZone: 'America/Costa_Rica',
    currency: 'Colon',
    languageCodes: 'es-CR,en',
  },
  {
    name: 'Croatia',
    iso2: 'HR',
    iso3: 'HRV',
    isoNumeric: '191',
    phoneCode: '385',
    continent: 'Europe',
    capital: 'Zagreb',
    timeZone: 'Europe/Belgrade',
    currency: 'Kuna',
    languageCodes: 'hr-HR,sr',
  },
  {
    name: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    isoNumeric: '192',
    phoneCode: '53',
    continent: 'North America',
    capital: 'Havana',
    timeZone: 'America/Havana',
    currency: 'Peso',
    languageCodes: 'es-CU',
  },
  {
    name: 'Curacao',
    iso2: 'CW',
    iso3: 'CUW',
    isoNumeric: '531',
    phoneCode: '599',
    continent: 'North America',
    capital: 'Willemstad',
    timeZone: 'America/Curacao',
    currency: 'Guilder',
    languageCodes: 'nl,pap',
  },
  {
    name: 'Cyprus',
    iso2: 'CY',
    iso3: 'CYP',
    isoNumeric: '196',
    phoneCode: '357',
    continent: 'Europe',
    capital: 'Nicosia',
    timeZone: 'Asia/Nicosia',
    currency: 'Euro',
    languageCodes: 'el-CY,tr-CY,en',
  },
  {
    name: 'Czech Republic',
    iso2: 'CZ',
    iso3: 'CZE',
    isoNumeric: '203',
    phoneCode: '420',
    continent: 'Europe',
    capital: 'Prague',
    timeZone: 'Europe/Prague',
    currency: 'Koruna',
    languageCodes: 'cs,sk',
  },
  {
    name: 'Democratic Republic of the Congo',
    iso2: 'CD',
    iso3: 'COD',
    isoNumeric: '180',
    phoneCode: '243',
    continent: 'Africa',
    capital: 'Kinshasa',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-CD,ln,kg',
  },
  {
    name: 'Denmark',
    iso2: 'DK',
    iso3: 'DNK',
    isoNumeric: '208',
    phoneCode: '45',
    continent: 'Europe',
    capital: 'Copenhagen',
    timeZone: 'Europe/Copenhagen',
    currency: 'Euro',
    languageCodes: 'da-DK,en,fo,de-DK',
  },
  {
    name: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
    isoNumeric: '262',
    phoneCode: '253',
    continent: 'Africa',
    capital: 'Djibouti',
    timeZone: 'Africa/Djibouti',
    currency: 'Franc',
    languageCodes: 'fr-DJ,ar,so-DJ,aa',
  },
  {
    name: 'Dominica',
    iso2: 'DM',
    iso3: 'DMA',
    isoNumeric: '212',
    phoneCode: '1-767',
    continent: 'North America',
    capital: 'Roseau',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-DM',
  },
  {
    name: 'Dominican Republic',
    iso2: 'DO',
    iso3: 'DOM',
    isoNumeric: '214',
    phoneCode: '1-809, 1-829, 1-849',
    continent: 'North America',
    capital: 'Santo Domingo',
    timeZone: 'America/Santo_Domingo',
    currency: 'Peso',
    languageCodes: 'es-DO',
  },
  {
    name: 'East Timor',
    iso2: 'TL',
    iso3: 'TLS',
    isoNumeric: '626',
    phoneCode: '670',
    continent: 'Oceania',
    capital: 'Dili',
    timeZone: 'Asia/Dili',
    currency: 'Dollar',
    languageCodes: 'tet,pt-TL,id,en',
  },
  {
    name: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
    isoNumeric: '218',
    phoneCode: '593',
    continent: 'South America',
    capital: 'Quito',
    timeZone: 'America/Guayaquil',
    currency: 'Dollar',
    languageCodes: 'es-EC',
  },
  {
    name: 'Egypt',
    iso2: 'EG',
    iso3: 'EGY',
    isoNumeric: '818',
    phoneCode: '20',
    continent: 'Africa',
    capital: 'Cairo',
    timeZone: 'Africa/Cairo',
    currency: 'Pound',
    languageCodes: 'ar-EG,en,fr',
  },
  {
    name: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    isoNumeric: '222',
    phoneCode: '503',
    continent: 'North America',
    capital: 'San Salvador',
    timeZone: 'America/El_Salvador',
    currency: 'Dollar',
    languageCodes: 'es-SV',
  },
  {
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    iso3: 'GNQ',
    isoNumeric: '226',
    phoneCode: '240',
    continent: 'Africa',
    capital: 'Malabo',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'es-GQ,fr',
  },
  {
    name: 'Eritrea',
    iso2: 'ER',
    iso3: 'ERI',
    isoNumeric: '232',
    phoneCode: '291',
    continent: 'Africa',
    capital: 'Asmara',
    timeZone: 'Africa/Asmara',
    currency: 'Nakfa',
    languageCodes: 'aa-ER,ar,tig,kun,ti-ER',
  },
  {
    name: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
    isoNumeric: '233',
    phoneCode: '372',
    continent: 'Europe',
    capital: 'Tallinn',
    timeZone: 'Europe/Tallinn',
    currency: 'Euro',
    languageCodes: 'et,ru',
  },
  {
    name: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
    isoNumeric: '231',
    phoneCode: '251',
    continent: 'Africa',
    capital: 'Addis Ababa',
    timeZone: 'Africa/Addis_Ababa',
    currency: 'Birr',
    languageCodes: 'am,en-ET,om-ET,ti-ET,so-ET,sid',
  },
  {
    name: 'Falkland Islands',
    iso2: 'FK',
    iso3: 'FLK',
    isoNumeric: '238',
    phoneCode: '500',
    continent: 'South America',
    capital: 'Stanley',
    timeZone: 'Atlantic/Stanley',
    currency: 'Pound',
    languageCodes: 'en-FK',
  },
  {
    name: 'Faroe Islands',
    iso2: 'FO',
    iso3: 'FRO',
    isoNumeric: '234',
    phoneCode: '298',
    continent: 'Europe',
    capital: 'Torshavn',
    timeZone: 'Atlantic/Faroe',
    currency: 'Krone',
    languageCodes: 'fo,da-FO',
  },
  {
    name: 'Fiji',
    iso2: 'FJ',
    iso3: 'FJI',
    isoNumeric: '242',
    phoneCode: '679',
    continent: 'Oceania',
    capital: 'Suva',
    timeZone: 'Pacific/Fiji',
    currency: 'Dollar',
    languageCodes: 'en-FJ,fj',
  },
  {
    name: 'Finland',
    iso2: 'FI',
    iso3: 'FIN',
    isoNumeric: '246',
    phoneCode: '358',
    continent: 'Europe',
    capital: 'Helsinki',
    timeZone: 'Europe/Helsinki',
    currency: 'Euro',
    languageCodes: 'fi-FI,sv-FI,smn',
  },
  {
    name: 'France',
    iso2: 'FR',
    iso3: 'FRA',
    isoNumeric: '250',
    phoneCode: '33',
    continent: 'Europe',
    capital: 'Paris',
    timeZone: 'Europe/Paris',
    currency: 'Euro',
    languageCodes: 'fr-FR,frp,br,co,ca,eu,oc',
  },
  {
    name: 'French Polynesia',
    iso2: 'PF',
    iso3: 'PYF',
    isoNumeric: '258',
    phoneCode: '689',
    continent: 'Oceania',
    capital: 'Papeete',
    timeZone: 'Pacific/Tahiti',
    currency: 'Franc',
    languageCodes: 'fr-PF,ty',
  },
  {
    name: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
    isoNumeric: '266',
    phoneCode: '241',
    continent: 'Africa',
    capital: 'Libreville',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-GA',
  },
  {
    name: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
    isoNumeric: '270',
    phoneCode: '220',
    continent: 'Africa',
    capital: 'Banjul',
    timeZone: 'Africa/Abidjan',
    currency: 'Dalasi',
    languageCodes: 'en-GM,mnk,wof,wo,ff',
  },
  {
    name: 'Georgia',
    iso2: 'GE',
    iso3: 'GEO',
    isoNumeric: '268',
    phoneCode: '995',
    continent: 'Asia',
    capital: 'Tbilisi',
    timeZone: 'Asia/Tbilisi',
    currency: 'Lari',
    languageCodes: 'ka,ru,hy,az',
  },
  {
    name: 'Germany',
    iso2: 'DE',
    iso3: 'DEU',
    isoNumeric: '276',
    phoneCode: '49',
    continent: 'Europe',
    capital: 'Berlin',
    timeZone: 'Europe/Berlin',
    currency: 'Euro',
    languageCodes: 'de',
  },
  {
    name: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
    isoNumeric: '288',
    phoneCode: '233',
    continent: 'Africa',
    capital: 'Accra',
    timeZone: 'Africa/Accra',
    currency: 'Cedi',
    languageCodes: 'en-GH,ak,ee,tw',
  },
  {
    name: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    isoNumeric: '292',
    phoneCode: '350',
    continent: 'Europe',
    capital: 'Gibraltar',
    timeZone: 'Europe/Gibraltar',
    currency: 'Pound',
    languageCodes: 'en-GI,es,it,pt',
  },
  {
    name: 'Greece',
    iso2: 'GR',
    iso3: 'GRC',
    isoNumeric: '300',
    phoneCode: '30',
    continent: 'Europe',
    capital: 'Athens',
    timeZone: 'Europe/Athens',
    currency: 'Euro',
    languageCodes: 'el-GR,en,fr',
  },
  {
    name: 'Greenland',
    iso2: 'GL',
    iso3: 'GRL',
    isoNumeric: '304',
    phoneCode: '299',
    continent: 'North America',
    capital: 'Nuuk',
    timeZone: 'America/Godthab',
    currency: 'Krone',
    languageCodes: 'kl,da-GL,en',
  },
  {
    name: 'Grenada',
    iso2: 'GD',
    iso3: 'GRD',
    isoNumeric: '308',
    phoneCode: '1-473',
    continent: 'North America',
    capital: "St. George's",
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-GD',
  },
  {
    name: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
    isoNumeric: '316',
    phoneCode: '1-671',
    continent: 'Oceania',
    capital: 'Hagatna',
    timeZone: 'Pacific/Guam',
    currency: 'Dollar',
    languageCodes: 'en-GU,ch-GU',
  },
  {
    name: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    isoNumeric: '320',
    phoneCode: '502',
    continent: 'North America',
    capital: 'Guatemala City',
    timeZone: 'America/Guatemala',
    currency: 'Quetzal',
    languageCodes: 'es-GT',
  },
  {
    name: 'Guernsey',
    iso2: 'GG',
    iso3: 'GGY',
    isoNumeric: '831',
    phoneCode: '44-1481',
    continent: 'Europe',
    capital: 'St Peter Port',
    timeZone: 'Europe/London',
    currency: 'Pound',
    languageCodes: 'en,fr',
  },
  {
    name: 'Guinea',
    iso2: 'GN',
    iso3: 'GIN',
    isoNumeric: '324',
    phoneCode: '224',
    continent: 'Africa',
    capital: 'Conakry',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-GN',
  },
  {
    name: 'Guinea-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
    isoNumeric: '624',
    phoneCode: '245',
    continent: 'Africa',
    capital: 'Bissau',
    timeZone: 'Africa/Bissau',
    currency: 'Franc',
    languageCodes: 'pt-GW,pov',
  },
  {
    name: 'Guyana',
    iso2: 'GY',
    iso3: 'GUY',
    isoNumeric: '328',
    phoneCode: '592',
    continent: 'South America',
    capital: 'Georgetown',
    timeZone: 'America/Guyana',
    currency: 'Dollar',
    languageCodes: 'en-GY',
  },
  {
    name: 'Haiti',
    iso2: 'HT',
    iso3: 'HTI',
    isoNumeric: '332',
    phoneCode: '509',
    continent: 'North America',
    capital: 'Port-au-Prince',
    timeZone: 'America/Port-au-Prince',
    currency: 'Gourde',
    languageCodes: 'ht,fr-HT',
  },
  {
    name: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    isoNumeric: '340',
    phoneCode: '504',
    continent: 'North America',
    capital: 'Tegucigalpa',
    timeZone: 'America/Tegucigalpa',
    currency: 'Lempira',
    languageCodes: 'es-HN',
  },
  {
    name: 'Hong Kong',
    iso2: 'HK',
    iso3: 'HKG',
    isoNumeric: '344',
    phoneCode: '852',
    continent: 'Asia',
    capital: 'Hong Kong',
    timeZone: 'Asia/Hong_Kong',
    currency: 'Dollar',
    languageCodes: 'zh-HK,yue,zh,en',
  },
  {
    name: 'Hungary',
    iso2: 'HU',
    iso3: 'HUN',
    isoNumeric: '348',
    phoneCode: '36',
    continent: 'Europe',
    capital: 'Budapest',
    timeZone: 'Europe/Budapest',
    currency: 'Forint',
    languageCodes: 'hu-HU',
  },
  {
    name: 'Iceland',
    iso2: 'IS',
    iso3: 'ISL',
    isoNumeric: '352',
    phoneCode: '354',
    continent: 'Europe',
    capital: 'Reykjavik',
    timeZone: 'Atlantic/Reykjavik',
    currency: 'Krona',
    languageCodes: 'is,en,de,da,sv,no',
  },
  {
    name: 'India',
    iso2: 'IN',
    iso3: 'IND',
    isoNumeric: '356',
    phoneCode: '91',
    continent: 'Asia',
    capital: 'New Delhi',
    timeZone: 'Asia/Kolkata',
    currency: 'Rupee',
    languageCodes:
      'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc',
  },
  {
    name: 'Indonesia',
    iso2: 'ID',
    iso3: 'IDN',
    isoNumeric: '360',
    phoneCode: '62',
    continent: 'Asia',
    capital: 'Jakarta',
    timeZone: 'Asia/Jakarta',
    currency: 'Rupiah',
    languageCodes: 'id,en,nl,jv',
  },
  {
    name: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
    isoNumeric: '364',
    phoneCode: '98',
    continent: 'Asia',
    capital: 'Tehran',
    timeZone: 'Asia/Tehran',
    currency: 'Rial',
    languageCodes: 'fa-IR,ku',
  },
  {
    name: 'Iraq',
    iso2: 'IQ',
    iso3: 'IRQ',
    isoNumeric: '368',
    phoneCode: '964',
    continent: 'Asia',
    capital: 'Baghdad',
    timeZone: 'Asia/Baghdad',
    currency: 'Dinar',
    languageCodes: 'ar-IQ,ku,hy',
  },
  {
    name: 'Ireland',
    iso2: 'IE',
    iso3: 'IRL',
    isoNumeric: '372',
    phoneCode: '353',
    continent: 'Europe',
    capital: 'Dublin',
    timeZone: 'Europe/Dublin',
    currency: 'Euro',
    languageCodes: 'en-IE,ga-IE',
  },
  {
    name: 'Isle of Man',
    iso2: 'IM',
    iso3: 'IMN',
    isoNumeric: '833',
    phoneCode: '44-1624',
    continent: 'Europe',
    capital: 'Douglas, Isle of Man',
    timeZone: 'Europe/London',
    currency: 'Pound',
    languageCodes: 'en,gv',
  },
  {
    name: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
    isoNumeric: '376',
    phoneCode: '972',
    continent: 'Asia',
    capital: 'Jerusalem',
    timeZone: 'Asia/Jerusalem',
    currency: 'Shekel',
    languageCodes: 'he,ar-IL,en-IL,',
  },
  {
    name: 'Italy',
    iso2: 'IT',
    iso3: 'ITA',
    isoNumeric: '380',
    phoneCode: '39',
    continent: 'Europe',
    capital: 'Rome',
    timeZone: 'Europe/Rome',
    currency: 'Euro',
    languageCodes: 'it-IT,de-IT,fr-IT,sc,ca,co,sl',
  },
  {
    name: 'Ivory Coast',
    iso2: 'CI',
    iso3: 'CIV',
    isoNumeric: '384',
    phoneCode: '225',
    continent: 'Africa',
    capital: 'Yamoussoukro',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-CI',
  },
  {
    name: 'Jamaica',
    iso2: 'JM',
    iso3: 'JAM',
    isoNumeric: '388',
    phoneCode: '1-876',
    continent: 'North America',
    capital: 'Kingston',
    timeZone: 'America/Jamaica',
    currency: 'Dollar',
    languageCodes: 'en-JM',
  },
  {
    name: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
    isoNumeric: '392',
    phoneCode: '81',
    continent: 'Asia',
    capital: 'Tokyo',
    timeZone: 'Asia/Tokyo',
    currency: 'Yen',
    languageCodes: 'ja',
  },
  {
    name: 'Jersey',
    iso2: 'JE',
    iso3: 'JEY',
    isoNumeric: '832',
    phoneCode: '44-1534',
    continent: 'Europe',
    capital: 'Saint Helier',
    timeZone: 'Europe/London',
    currency: 'Pound',
    languageCodes: 'en,pt',
  },
  {
    name: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
    isoNumeric: '400',
    phoneCode: '962',
    continent: 'Asia',
    capital: 'Amman',
    timeZone: 'Asia/Amman',
    currency: 'Dinar',
    languageCodes: 'ar-JO,en',
  },
  {
    name: 'Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
    isoNumeric: '398',
    phoneCode: '7',
    continent: 'Asia',
    capital: 'Astana',
    timeZone: 'Asia/Almaty',
    currency: 'Tenge',
    languageCodes: 'kk,ru',
  },
  {
    name: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    isoNumeric: '404',
    phoneCode: '254',
    continent: 'Africa',
    capital: 'Nairobi',
    timeZone: 'Africa/Nairobi',
    currency: 'Shilling',
    languageCodes: 'en-KE,sw-KE',
  },
  {
    name: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    isoNumeric: '296',
    phoneCode: '686',
    continent: 'Oceania',
    capital: 'Tarawa',
    timeZone: 'Pacific/Tarawa',
    currency: 'Dollar',
    languageCodes: 'en-KI,gil',
  },
  {
    name: 'Kosovo',
    iso2: 'XK',
    iso3: 'XKX',
    isoNumeric: '0',
    phoneCode: '383',
    continent: 'Europe',
    capital: 'Pristina',
    timeZone: 'Europe/Belgrade',
    currency: 'Euro',
    languageCodes: 'sq,sr',
  },
  {
    name: 'Kuwait',
    iso2: 'KW',
    iso3: 'KWT',
    isoNumeric: '414',
    phoneCode: '965',
    continent: 'Asia',
    capital: 'Kuwait City',
    timeZone: 'Asia/Kuwait',
    currency: 'Dinar',
    languageCodes: 'ar-KW,en',
  },
  {
    name: 'Kyrgyzstan',
    iso2: 'KG',
    iso3: 'KGZ',
    isoNumeric: '417',
    phoneCode: '996',
    continent: 'Asia',
    capital: 'Bishkek',
    timeZone: 'Asia/Bishkek',
    currency: 'Som',
    languageCodes: 'ky,uz,ru',
  },
  {
    name: 'Laos',
    iso2: 'LA',
    iso3: 'LAO',
    isoNumeric: '418',
    phoneCode: '856',
    continent: 'Asia',
    capital: 'Vientiane',
    timeZone: 'Asia/Vientiane',
    currency: 'Kip',
    languageCodes: 'lo,fr,en',
  },
  {
    name: 'Latvia',
    iso2: 'LV',
    iso3: 'LVA',
    isoNumeric: '428',
    phoneCode: '371',
    continent: 'Europe',
    capital: 'Riga',
    timeZone: 'Europe/Riga',
    currency: 'Euro',
    languageCodes: 'lv,ru,lt',
  },
  {
    name: 'Lebanon',
    iso2: 'LB',
    iso3: 'LBN',
    isoNumeric: '422',
    phoneCode: '961',
    continent: 'Asia',
    capital: 'Beirut',
    timeZone: 'Asia/Beirut',
    currency: 'Pound',
    languageCodes: 'ar-LB,fr-LB,en,hy',
  },
  {
    name: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    isoNumeric: '426',
    phoneCode: '266',
    continent: 'Africa',
    capital: 'Maseru',
    timeZone: 'Africa/Johannesburg',
    currency: 'Loti',
    languageCodes: 'en-LS,st,zu,xh',
  },
  {
    name: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
    isoNumeric: '430',
    phoneCode: '231',
    continent: 'Africa',
    capital: 'Monrovia',
    timeZone: 'Africa/Monrovia',
    currency: 'Dollar',
    languageCodes: 'en-LR',
  },
  {
    name: 'Libya',
    iso2: 'LY',
    iso3: 'LBY',
    isoNumeric: '434',
    phoneCode: '218',
    continent: 'Africa',
    capital: 'Tripolis',
    timeZone: 'Africa/Tripoli',
    currency: 'Dinar',
    languageCodes: 'ar-LY,it,en',
  },
  {
    name: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
    isoNumeric: '438',
    phoneCode: '423',
    continent: 'Europe',
    capital: 'Vaduz',
    timeZone: 'Europe/Zurich',
    currency: 'Franc',
    languageCodes: 'de-LI',
  },
  {
    name: 'Lithuania',
    iso2: 'LT',
    iso3: 'LTU',
    isoNumeric: '440',
    phoneCode: '370',
    continent: 'Europe',
    capital: 'Vilnius',
    timeZone: 'Europe/Vilnius',
    currency: 'Euro',
    languageCodes: 'lt,ru,pl',
  },
  {
    name: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
    isoNumeric: '442',
    phoneCode: '352',
    continent: 'Europe',
    capital: 'Luxembourg',
    timeZone: 'Europe/Luxembourg',
    currency: 'Euro',
    languageCodes: 'lb,de-LU,fr-LU',
  },
  {
    name: 'Macau',
    iso2: 'MO',
    iso3: 'MAC',
    isoNumeric: '446',
    phoneCode: '853',
    continent: 'Asia',
    capital: 'Macao',
    timeZone: 'Asia/Macau',
    currency: 'Pataca',
    languageCodes: 'zh,zh-MO,pt',
  },
  {
    name: 'Macedonia',
    iso2: 'MK',
    iso3: 'MKD',
    isoNumeric: '807',
    phoneCode: '389',
    continent: 'Europe',
    capital: 'Skopje',
    timeZone: 'Europe/Belgrade',
    currency: 'Denar',
    languageCodes: 'mk,sq,tr,rmm,sr',
  },
  {
    name: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
    isoNumeric: '450',
    phoneCode: '261',
    continent: 'Africa',
    capital: 'Antananarivo',
    timeZone: 'Indian/Antananarivo',
    currency: 'Ariary',
    languageCodes: 'fr-MG,mg',
  },
  {
    name: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    isoNumeric: '454',
    phoneCode: '265',
    continent: 'Africa',
    capital: 'Lilongwe',
    timeZone: 'Africa/Maputo',
    currency: 'Kwacha',
    languageCodes: 'ny,yao,tum,swk',
  },
  {
    name: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
    isoNumeric: '458',
    phoneCode: '60',
    continent: 'Asia',
    capital: 'Kuala Lumpur',
    timeZone: 'Asia/Kuala_Lumpur',
    currency: 'Ringgit',
    languageCodes: 'ms-MY,en,zh,ta,te,ml,pa,th',
  },
  {
    name: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    isoNumeric: '462',
    phoneCode: '960',
    continent: 'Asia',
    capital: 'Male',
    timeZone: 'Indian/Maldives',
    currency: 'Rufiyaa',
    languageCodes: 'dv,en',
  },
  {
    name: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
    isoNumeric: '466',
    phoneCode: '223',
    continent: 'Africa',
    capital: 'Bamako',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-ML,bm',
  },
  {
    name: 'Malta',
    iso2: 'MT',
    iso3: 'MLT',
    isoNumeric: '470',
    phoneCode: '356',
    continent: 'Europe',
    capital: 'Valletta',
    timeZone: 'Europe/Malta',
    currency: 'Euro',
    languageCodes: 'mt,en-MT',
  },
  {
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    isoNumeric: '584',
    phoneCode: '692',
    continent: 'Oceania',
    capital: 'Majuro',
    timeZone: 'Pacific/Majuro',
    currency: 'Dollar',
    languageCodes: 'mh,en-MH',
  },
  {
    name: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
    isoNumeric: '478',
    phoneCode: '222',
    continent: 'Africa',
    capital: 'Nouakchott',
    timeZone: 'Africa/Abidjan',
    currency: 'Ouguiya',
    languageCodes: 'ar-MR,fuc,snk,fr,mey,wo',
  },
  {
    name: 'Mauritius',
    iso2: 'MU',
    iso3: 'MUS',
    isoNumeric: '480',
    phoneCode: '230',
    continent: 'Africa',
    capital: 'Port Louis',
    timeZone: 'Indian/Mauritius',
    currency: 'Rupee',
    languageCodes: 'en-MU,bho,fr',
  },
  {
    name: 'Mayotte',
    iso2: 'YT',
    iso3: 'MYT',
    isoNumeric: '175',
    phoneCode: '262',
    continent: 'Africa',
    capital: 'Mamoudzou',
    timeZone: 'Indian/Mayotte',
    currency: 'Euro',
    languageCodes: 'fr-YT',
  },
  {
    name: 'Mexico',
    iso2: 'MX',
    iso3: 'MEX',
    isoNumeric: '484',
    phoneCode: '52',
    continent: 'North America',
    capital: 'Mexico City',
    timeZone: 'America/Mexico_City',
    currency: 'Peso',
    languageCodes: 'es-MX',
  },
  {
    name: 'Micronesia',
    iso2: 'FM',
    iso3: 'FSM',
    isoNumeric: '583',
    phoneCode: '691',
    continent: 'Oceania',
    capital: 'Palikir',
    timeZone: 'Pacific/Pohnpei',
    currency: 'Dollar',
    languageCodes: 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg',
  },
  {
    name: 'Moldova',
    iso2: 'MD',
    iso3: 'MDA',
    isoNumeric: '498',
    phoneCode: '373',
    continent: 'Europe',
    capital: 'Chisinau',
    timeZone: 'Europe/Chisinau',
    currency: 'Leu',
    languageCodes: 'ro,ru,gag,tr',
  },
  {
    name: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
    isoNumeric: '492',
    phoneCode: '377',
    continent: 'Europe',
    capital: 'Monaco',
    timeZone: 'Europe/Monaco',
    currency: 'Euro',
    languageCodes: 'fr-MC,en,it',
  },
  {
    name: 'Mongolia',
    iso2: 'MN',
    iso3: 'MNG',
    isoNumeric: '496',
    phoneCode: '976',
    continent: 'Asia',
    capital: 'Ulan Bator',
    timeZone: 'Asia/Ulaanbaatar',
    currency: 'Tugrik',
    languageCodes: 'mn,ru',
  },
  {
    name: 'Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
    isoNumeric: '499',
    phoneCode: '382',
    continent: 'Europe',
    capital: 'Podgorica',
    timeZone: 'Europe/Belgrade',
    currency: 'Euro',
    languageCodes: 'sr,hu,bs,sq,hr,rom',
  },
  {
    name: 'Montserrat',
    iso2: 'MS',
    iso3: 'MSR',
    isoNumeric: '500',
    phoneCode: '1-664',
    continent: 'North America',
    capital: 'Plymouth',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-MS',
  },
  {
    name: 'Morocco',
    iso2: 'MA',
    iso3: 'MAR',
    isoNumeric: '504',
    phoneCode: '212',
    continent: 'Africa',
    capital: 'Rabat',
    timeZone: 'Africa/Casablanca',
    currency: 'Dirham',
    languageCodes: 'ar-MA,fr',
  },
  {
    name: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
    isoNumeric: '508',
    phoneCode: '258',
    continent: 'Africa',
    capital: 'Maputo',
    timeZone: 'Africa/Maputo',
    currency: 'Metical',
    languageCodes: 'pt-MZ,vmw',
  },
  {
    name: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    isoNumeric: '104',
    phoneCode: '95',
    continent: 'Asia',
    capital: 'Nay Pyi Taw',
    timeZone: 'Asia/Rangoon',
    currency: 'Kyat',
    languageCodes: 'my',
  },
  {
    name: 'Namibia',
    iso2: 'NA',
    iso3: 'NAM',
    isoNumeric: '516',
    phoneCode: '264',
    continent: 'Africa',
    capital: 'Windhoek',
    timeZone: 'Africa/Windhoek',
    currency: 'Dollar',
    languageCodes: 'en-NA,af,de,hz,naq',
  },
  {
    name: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
    isoNumeric: '520',
    phoneCode: '674',
    continent: 'Oceania',
    capital: 'Yaren',
    timeZone: 'Pacific/Nauru',
    currency: 'Dollar',
    languageCodes: 'na,en-NR',
  },
  {
    name: 'Nepal',
    iso2: 'NP',
    iso3: 'NPL',
    isoNumeric: '524',
    phoneCode: '977',
    continent: 'Asia',
    capital: 'Kathmandu',
    timeZone: 'Asia/Kathmandu',
    currency: 'Rupee',
    languageCodes: 'ne,en',
  },
  {
    name: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
    isoNumeric: '528',
    phoneCode: '31',
    continent: 'Europe',
    capital: 'Amsterdam',
    timeZone: 'Europe/Amsterdam',
    currency: 'Euro',
    languageCodes: 'nl-NL,fy-NL',
  },
  {
    name: 'Netherlands Antilles',
    iso2: 'AN',
    iso3: 'ANT',
    isoNumeric: '530',
    phoneCode: '599',
    continent: 'North America',
    capital: 'Willemstad',
    timeZone: 'America/Curacao',
    currency: 'Guilder',
    languageCodes: 'nl-AN,en,es',
  },
  {
    name: 'New Caledonia',
    iso2: 'NC',
    iso3: 'NCL',
    isoNumeric: '540',
    phoneCode: '687',
    continent: 'Oceania',
    capital: 'Noumea',
    timeZone: 'Pacific/Noumea',
    currency: 'Franc',
    languageCodes: 'fr-NC',
  },
  {
    name: 'New Zealand',
    iso2: 'NZ',
    iso3: 'NZL',
    isoNumeric: '554',
    phoneCode: '64',
    continent: 'Oceania',
    capital: 'Wellington',
    timeZone: 'Pacific/Auckland',
    currency: 'Dollar',
    languageCodes: 'en-NZ,mi',
  },
  {
    name: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    isoNumeric: '558',
    phoneCode: '505',
    continent: 'North America',
    capital: 'Managua',
    timeZone: 'America/Managua',
    currency: 'Cordoba',
    languageCodes: 'es-NI,en',
  },
  {
    name: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
    isoNumeric: '562',
    phoneCode: '227',
    continent: 'Africa',
    capital: 'Niamey',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-NE,ha,kr,dje',
  },
  {
    name: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
    isoNumeric: '566',
    phoneCode: '234',
    continent: 'Africa',
    capital: 'Abuja',
    timeZone: 'Africa/Lagos',
    currency: 'Naira',
    status: true,
    languageCodes: 'en-NG,ha,yo,ig,ff',
  },
  {
    name: 'Niue',
    iso2: 'NU',
    iso3: 'NIU',
    isoNumeric: '570',
    phoneCode: '683',
    continent: 'Oceania',
    capital: 'Alofi',
    timeZone: 'Pacific/Niue',
    currency: 'Dollar',
    languageCodes: 'niu,en-NU',
  },
  {
    name: 'North Korea',
    iso2: 'KP',
    iso3: 'PRK',
    isoNumeric: '408',
    phoneCode: '850',
    continent: 'Asia',
    capital: 'Pyongyang',
    timeZone: 'Asia/Pyongyang',
    currency: 'Won',
    languageCodes: 'ko-KP',
  },
  {
    name: 'Northern Mariana Islands',
    iso2: 'MP',
    iso3: 'MNP',
    isoNumeric: '580',
    phoneCode: '1-670',
    continent: 'Oceania',
    capital: 'Saipan',
    timeZone: 'Pacific/Saipan',
    currency: 'Dollar',
    languageCodes: 'fil,tl,zh,ch-MP,en-MP',
  },
  {
    name: 'Norway',
    iso2: 'NO',
    iso3: 'NOR',
    isoNumeric: '578',
    phoneCode: '47',
    continent: 'Europe',
    capital: 'Oslo',
    timeZone: 'Europe/Oslo',
    currency: 'Krone',
    languageCodes: 'no,nb,nn,se,fi',
  },
  {
    name: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
    isoNumeric: '512',
    phoneCode: '968',
    continent: 'Asia',
    capital: 'Muscat',
    timeZone: 'Asia/Muscat',
    currency: 'Rial',
    languageCodes: 'ar-OM,en,bal,ur',
  },
  {
    name: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    isoNumeric: '586',
    phoneCode: '92',
    continent: 'Asia',
    capital: 'Islamabad',
    timeZone: 'Asia/Karachi',
    currency: 'Rupee',
    languageCodes: 'ur-PK,en-PK,pa,sd,ps,brh',
  },
  {
    name: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
    isoNumeric: '585',
    phoneCode: '680',
    continent: 'Oceania',
    capital: 'Melekeok',
    timeZone: 'Pacific/Palau',
    currency: 'Dollar',
    languageCodes: 'pau,sov,en-PW,tox,ja,fil,zh',
  },
  {
    name: 'Palestine',
    iso2: 'PS',
    iso3: 'PSE',
    isoNumeric: '275',
    phoneCode: '970',
    continent: 'Asia',
    capital: 'East Jerusalem',
    timeZone: 'Asia/Hebron',
    currency: 'Shekel',
    languageCodes: 'ar-PS',
  },
  {
    name: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    isoNumeric: '591',
    phoneCode: '507',
    continent: 'North America',
    capital: 'Panama City',
    timeZone: 'America/Panama',
    currency: 'Balboa',
    languageCodes: 'es-PA,en',
  },
  {
    name: 'Papua New Guinea',
    iso2: 'PG',
    iso3: 'PNG',
    isoNumeric: '598',
    phoneCode: '675',
    continent: 'Oceania',
    capital: 'Port Moresby',
    timeZone: 'Pacific/Port_Moresby',
    currency: 'Kina',
    languageCodes: 'en-PG,ho,meu,tpi',
  },
  {
    name: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    isoNumeric: '600',
    phoneCode: '595',
    continent: 'South America',
    capital: 'Asuncion',
    timeZone: 'America/Asuncion',
    currency: 'Guarani',
    languageCodes: 'es-PY,gn',
  },
  {
    name: 'Peru',
    iso2: 'PE',
    iso3: 'PER',
    isoNumeric: '604',
    phoneCode: '51',
    continent: 'South America',
    capital: 'Lima',
    timeZone: 'America/Lima',
    currency: 'Sol',
    languageCodes: 'es-PE,qu,ay',
  },
  {
    name: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    isoNumeric: '608',
    phoneCode: '63',
    continent: 'Asia',
    capital: 'Manila',
    timeZone: 'Asia/Manila',
    currency: 'Peso',
    languageCodes: 'tl,en-PH,fil',
  },
  {
    name: 'Pitcairn',
    iso2: 'PN',
    iso3: 'PCN',
    isoNumeric: '612',
    phoneCode: '64',
    continent: 'Oceania',
    capital: 'Adamstown',
    timeZone: 'Pacific/Pitcairn',
    currency: 'Dollar',
    languageCodes: 'en-PN',
  },
  {
    name: 'Poland',
    iso2: 'PL',
    iso3: 'POL',
    isoNumeric: '616',
    phoneCode: '48',
    continent: 'Europe',
    capital: 'Warsaw',
    timeZone: 'Europe/Warsaw',
    currency: 'Zloty',
    languageCodes: 'pl',
  },
  {
    name: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
    isoNumeric: '620',
    phoneCode: '351',
    continent: 'Europe',
    capital: 'Lisbon',
    timeZone: 'Europe/Lisbon',
    currency: 'Euro',
    languageCodes: 'pt-PT,mwl',
  },
  {
    name: 'Puerto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    isoNumeric: '630',
    phoneCode: '1-787, 1-939',
    continent: 'North America',
    capital: 'San Juan',
    timeZone: 'America/Puerto_Rico',
    currency: 'Dollar',
    languageCodes: 'en-PR,es-PR',
  },
  {
    name: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
    isoNumeric: '634',
    phoneCode: '974',
    continent: 'Asia',
    capital: 'Doha',
    timeZone: 'Asia/Qatar',
    currency: 'Rial',
    languageCodes: 'ar-QA,es',
  },
  {
    name: 'Republic of the Congo',
    iso2: 'CG',
    iso3: 'COG',
    isoNumeric: '178',
    phoneCode: '242',
    continent: 'Africa',
    capital: 'Brazzaville',
    timeZone: 'Africa/Lagos',
    currency: 'Franc',
    languageCodes: 'fr-CG,kg,ln-CG',
  },
  {
    name: 'Reunion',
    iso2: 'RE',
    iso3: 'REU',
    isoNumeric: '638',
    phoneCode: '262',
    continent: 'Africa',
    capital: 'Saint-Denis',
    timeZone: 'Indian/Reunion',
    currency: 'Euro',
    languageCodes: 'fr-RE',
  },
  {
    name: 'Romania',
    iso2: 'RO',
    iso3: 'ROU',
    isoNumeric: '642',
    phoneCode: '40',
    continent: 'Europe',
    capital: 'Bucharest',
    timeZone: 'Europe/Bucharest',
    currency: 'Leu',
    languageCodes: 'ro,hu,rom',
  },
  {
    name: 'Russia',
    iso2: 'RU',
    iso3: 'RUS',
    isoNumeric: '643',
    phoneCode: '7',
    continent: 'Europe',
    capital: 'Moscow',
    timeZone: 'Europe/Moscow',
    currency: 'Ruble',
    languageCodes:
      'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog',
  },
  {
    name: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
    isoNumeric: '646',
    phoneCode: '250',
    continent: 'Africa',
    capital: 'Kigali',
    timeZone: 'Africa/Maputo',
    currency: 'Franc',
    languageCodes: 'rw,en-RW,fr-RW,sw',
  },
  {
    name: 'Saint Barthelemy',
    iso2: 'BL',
    iso3: 'BLM',
    isoNumeric: '652',
    phoneCode: '590',
    continent: 'North America',
    capital: 'Gustavia',
    timeZone: 'America/Port_of_Spain',
    currency: 'Euro',
    languageCodes: 'fr',
  },
  {
    name: 'Saint Helena',
    iso2: 'SH',
    iso3: 'SHN',
    isoNumeric: '654',
    phoneCode: '290',
    continent: 'Africa',
    capital: 'Jamestown',
    timeZone: 'Africa/Abidjan',
    currency: 'Pound',
    languageCodes: 'en-SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    isoNumeric: '659',
    phoneCode: '1-869',
    continent: 'North America',
    capital: 'Basseterre',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-KN',
  },
  {
    name: 'Saint Lucia',
    iso2: 'LC',
    iso3: 'LCA',
    isoNumeric: '662',
    phoneCode: '1-758',
    continent: 'North America',
    capital: 'Castries',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-LC',
  },
  {
    name: 'Saint Martin',
    iso2: 'MF',
    iso3: 'MAF',
    isoNumeric: '663',
    phoneCode: '590',
    continent: 'North America',
    capital: 'Marigot',
    timeZone: 'America/Port_of_Spain',
    currency: 'Euro',
    languageCodes: 'fr',
  },
  {
    name: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
    isoNumeric: '666',
    phoneCode: '508',
    continent: 'North America',
    capital: 'Saint-Pierre',
    timeZone: 'America/Miquelon',
    currency: 'Euro',
    languageCodes: 'fr-PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    isoNumeric: '670',
    phoneCode: '1-784',
    continent: 'North America',
    capital: 'Kingstown',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-VC,fr',
  },
  {
    name: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
    isoNumeric: '882',
    phoneCode: '685',
    continent: 'Oceania',
    capital: 'Apia',
    timeZone: 'Pacific/Apia',
    currency: 'Tala',
    languageCodes: 'sm,en-WS',
  },
  {
    name: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    isoNumeric: '674',
    phoneCode: '378',
    continent: 'Europe',
    capital: 'San Marino',
    timeZone: 'Europe/Rome',
    currency: 'Euro',
    languageCodes: 'it-SM',
  },
  {
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
    isoNumeric: '678',
    phoneCode: '239',
    continent: 'Africa',
    capital: 'Sao Tome',
    timeZone: 'Africa/Abidjan',
    currency: 'Dobra',
    languageCodes: 'pt-ST',
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    isoNumeric: '682',
    phoneCode: '966',
    continent: 'Asia',
    capital: 'Riyadh',
    timeZone: 'Asia/Riyadh',
    currency: 'Rial',
    languageCodes: 'ar-SA',
  },
  {
    name: 'Senegal',
    iso2: 'SN',
    iso3: 'SEN',
    isoNumeric: '686',
    phoneCode: '221',
    continent: 'Africa',
    capital: 'Dakar',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-SN,wo,fuc,mnk',
  },
  {
    name: 'Serbia',
    iso2: 'RS',
    iso3: 'SRB',
    isoNumeric: '688',
    phoneCode: '381',
    continent: 'Europe',
    capital: 'Belgrade',
    timeZone: 'Europe/Belgrade',
    currency: 'Dinar',
    languageCodes: 'sr,hu,bs,rom',
  },
  {
    name: 'Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
    isoNumeric: '690',
    phoneCode: '248',
    continent: 'Africa',
    capital: 'Victoria',
    timeZone: 'Indian/Mahe',
    currency: 'Rupee',
    languageCodes: 'en-SC,fr-SC',
  },
  {
    name: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    isoNumeric: '694',
    phoneCode: '232',
    continent: 'Africa',
    capital: 'Freetown',
    timeZone: 'Africa/Abidjan',
    currency: 'Leone',
    languageCodes: 'en-SL,men,tem',
  },
  {
    name: 'Singapore',
    iso2: 'SG',
    iso3: 'SGP',
    isoNumeric: '702',
    phoneCode: '65',
    continent: 'Asia',
    capital: 'Singapore',
    timeZone: 'Asia/Singapore',
    currency: 'Dollar',
    languageCodes: 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
  },
  {
    name: 'Sint Maarten',
    iso2: 'SX',
    iso3: 'SXM',
    isoNumeric: '534',
    phoneCode: '1-721',
    continent: 'North America',
    capital: 'Philipsburg',
    timeZone: 'America/Curacao',
    currency: 'Guilder',
    languageCodes: 'nl,en',
  },
  {
    name: 'Slovakia',
    iso2: 'SK',
    iso3: 'SVK',
    isoNumeric: '703',
    phoneCode: '421',
    continent: 'Europe',
    capital: 'Bratislava',
    timeZone: 'Europe/Prague',
    currency: 'Euro',
    languageCodes: 'sk,hu',
  },
  {
    name: 'Slovenia',
    iso2: 'SI',
    iso3: 'SVN',
    isoNumeric: '705',
    phoneCode: '386',
    continent: 'Europe',
    capital: 'Ljubljana',
    timeZone: 'Europe/Belgrade',
    currency: 'Euro',
    languageCodes: 'sl,sh',
  },
  {
    name: 'Solomon Islands',
    iso2: 'SB',
    iso3: 'SLB',
    isoNumeric: '90',
    phoneCode: '677',
    continent: 'Oceania',
    capital: 'Honiara',
    timeZone: 'Pacific/Guadalcanal',
    currency: 'Dollar',
    languageCodes: 'en-SB,tpi',
  },
  {
    name: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
    isoNumeric: '706',
    phoneCode: '252',
    continent: 'Africa',
    capital: 'Mogadishu',
    timeZone: 'Africa/Mogadishu',
    currency: 'Shilling',
    languageCodes: 'so-SO,ar-SO,it,en-SO',
  },
  {
    name: 'South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    isoNumeric: '710',
    phoneCode: '27',
    continent: 'Africa',
    capital: 'Pretoria',
    timeZone: 'Africa/Johannesburg',
    currency: 'Rand',
    languageCodes: 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr',
  },
  {
    name: 'South Korea',
    iso2: 'KR',
    iso3: 'KOR',
    isoNumeric: '410',
    phoneCode: '82',
    continent: 'Asia',
    capital: 'Seoul',
    timeZone: 'Asia/Seoul',
    currency: 'Won',
    languageCodes: 'ko-KR,en',
  },
  {
    name: 'South Sudan',
    iso2: 'SS',
    iso3: 'SSD',
    isoNumeric: '728',
    phoneCode: '211',
    continent: 'Africa',
    capital: 'Juba',
    timeZone: 'Africa/Khartoum',
    currency: 'Pound',
    languageCodes: 'en',
  },
  {
    name: 'Spain',
    iso2: 'ES',
    iso3: 'ESP',
    isoNumeric: '724',
    phoneCode: '34',
    continent: 'Europe',
    capital: 'Madrid',
    timeZone: 'Europe/Madrid',
    currency: 'Euro',
    languageCodes: 'es-ES,ca,gl,eu,oc',
  },
  {
    name: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    isoNumeric: '144',
    phoneCode: '94',
    continent: 'Asia',
    capital: 'Colombo',
    timeZone: 'Asia/Colombo',
    currency: 'Rupee',
    languageCodes: 'si,ta,en',
  },
  {
    name: 'Sudan',
    iso2: 'SD',
    iso3: 'SDN',
    isoNumeric: '729',
    phoneCode: '249',
    continent: 'Africa',
    capital: 'Khartoum',
    timeZone: 'Africa/Khartoum',
    currency: 'Pound',
    languageCodes: 'ar-SD,en,fia',
  },
  {
    name: 'Suriname',
    iso2: 'SR',
    iso3: 'SUR',
    isoNumeric: '740',
    phoneCode: '597',
    continent: 'South America',
    capital: 'Paramaribo',
    timeZone: 'America/Paramaribo',
    currency: 'Dollar',
    languageCodes: 'nl-SR,en,srn,hns,jv',
  },
  {
    name: 'Svalbard and Jan Mayen',
    iso2: 'SJ',
    iso3: 'SJM',
    isoNumeric: '744',
    phoneCode: '47',
    continent: 'Europe',
    capital: 'Longyearbyen',
    timeZone: 'Europe/Oslo',
    currency: 'Krone',
    languageCodes: 'no,ru',
  },
  {
    name: 'Swaziland',
    iso2: 'SZ',
    iso3: 'SWZ',
    isoNumeric: '748',
    phoneCode: '268',
    continent: 'Africa',
    capital: 'Mbabane',
    timeZone: 'Africa/Johannesburg',
    currency: 'Lilangeni',
    languageCodes: 'en-SZ,ss-SZ',
  },
  {
    name: 'Sweden',
    iso2: 'SE',
    iso3: 'SWE',
    isoNumeric: '752',
    phoneCode: '46',
    continent: 'Europe',
    capital: 'Stockholm',
    timeZone: 'Europe/Stockholm',
    currency: 'Krona',
    languageCodes: 'sv-SE,se,sma,fi-SE',
  },
  {
    name: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    isoNumeric: '756',
    phoneCode: '41',
    continent: 'Europe',
    capital: 'Berne',
    timeZone: 'Europe/Zurich',
    currency: 'Franc',
    languageCodes: 'de-CH,fr-CH,it-CH,rm',
  },
  {
    name: 'Syria',
    iso2: 'SY',
    iso3: 'SYR',
    isoNumeric: '760',
    phoneCode: '963',
    continent: 'Asia',
    capital: 'Damascus',
    timeZone: 'Asia/Damascus',
    currency: 'Pound',
    languageCodes: 'ar-SY,ku,hy,arc,fr,en',
  },
  {
    name: 'Taiwan',
    iso2: 'TW',
    iso3: 'TWN',
    isoNumeric: '158',
    phoneCode: '886',
    continent: 'Asia',
    capital: 'Taipei',
    timeZone: 'Asia/Taipei',
    currency: 'Dollar',
    languageCodes: 'zh-TW,zh,nan,hak',
  },
  {
    name: 'Tajikistan',
    iso2: 'TJ',
    iso3: 'TJK',
    isoNumeric: '762',
    phoneCode: '992',
    continent: 'Asia',
    capital: 'Dushanbe',
    timeZone: 'Asia/Dushanbe',
    currency: 'Somoni',
    languageCodes: 'tg,ru',
  },
  {
    name: 'Tanzania',
    iso2: 'TZ',
    iso3: 'TZA',
    isoNumeric: '834',
    phoneCode: '255',
    continent: 'Africa',
    capital: 'Dodoma',
    timeZone: 'Africa/Dar_es_Salaam',
    currency: 'Shilling',
    languageCodes: 'sw-TZ,en,ar',
  },
  {
    name: 'Thailand',
    iso2: 'TH',
    iso3: 'THA',
    isoNumeric: '764',
    phoneCode: '66',
    continent: 'Asia',
    capital: 'Bangkok',
    timeZone: 'Asia/Bangkok',
    currency: 'Baht',
    languageCodes: 'th,en',
  },
  {
    name: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
    isoNumeric: '768',
    phoneCode: '228',
    continent: 'Africa',
    capital: 'Lome',
    timeZone: 'Africa/Abidjan',
    currency: 'Franc',
    languageCodes: 'fr-TG,ee,hna,kbp,dag,ha',
  },
  {
    name: 'Tokelau',
    iso2: 'TK',
    iso3: 'TKL',
    isoNumeric: '772',
    phoneCode: '690',
    continent: 'Oceania',
    capital: '',
    timeZone: 'Pacific/Fakaofo',
    currency: 'Dollar',
    languageCodes: 'tkl,en-TK',
  },
  {
    name: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
    isoNumeric: '776',
    phoneCode: '676',
    continent: 'Oceania',
    capital: "Nuku'alofa",
    timeZone: 'Pacific/Tongatapu',
    currency: "Pa'anga",
    languageCodes: 'to,en-TO',
  },
  {
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    isoNumeric: '780',
    phoneCode: '1-868',
    continent: 'North America',
    capital: 'Port of Spain',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-TT,hns,fr,es,zh',
  },
  {
    name: 'Tunisia',
    iso2: 'TN',
    iso3: 'TUN',
    isoNumeric: '788',
    phoneCode: '216',
    continent: 'Africa',
    capital: 'Tunis',
    timeZone: 'Africa/Tunis',
    currency: 'Dinar',
    languageCodes: 'ar-TN,fr',
  },
  {
    name: 'Turkey',
    iso2: 'TR',
    iso3: 'TUR',
    isoNumeric: '792',
    phoneCode: '90',
    continent: 'Asia',
    capital: 'Ankara',
    timeZone: 'Europe/Istanbul',
    currency: 'Lira',
    languageCodes: 'tr-TR,ku,diq,az,av',
  },
  {
    name: 'Turkmenistan',
    iso2: 'TM',
    iso3: 'TKM',
    isoNumeric: '795',
    phoneCode: '993',
    continent: 'Asia',
    capital: 'Ashgabat',
    timeZone: 'Asia/Ashgabat',
    currency: 'Manat',
    languageCodes: 'tk,ru,uz',
  },
  {
    name: 'Turks and Caicos Islands',
    iso2: 'TC',
    iso3: 'TCA',
    isoNumeric: '796',
    phoneCode: '1-649',
    continent: 'North America',
    capital: 'Cockburn Town',
    timeZone: 'America/Grand_Turk',
    currency: 'Dollar',
    languageCodes: 'en-TC',
  },
  {
    name: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
    isoNumeric: '798',
    phoneCode: '688',
    continent: 'Oceania',
    capital: 'Funafuti',
    timeZone: 'Pacific/Funafuti',
    currency: 'Dollar',
    languageCodes: 'tvl,en,sm,gil',
  },
  {
    name: 'U.S. Virgin Islands',
    iso2: 'VI',
    iso3: 'VIR',
    isoNumeric: '850',
    phoneCode: '1-340',
    continent: 'North America',
    capital: 'Charlotte Amalie',
    timeZone: 'America/Port_of_Spain',
    currency: 'Dollar',
    languageCodes: 'en-VI',
  },
  {
    name: 'Uganda',
    iso2: 'UG',
    iso3: 'UGA',
    isoNumeric: '800',
    phoneCode: '256',
    continent: 'Africa',
    capital: 'Kampala',
    timeZone: 'Africa/Kampala',
    currency: 'Shilling',
    languageCodes: 'en-UG,lg,sw,ar',
  },
  {
    name: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    isoNumeric: '804',
    phoneCode: '380',
    continent: 'Europe',
    capital: 'Kiev',
    timeZone: 'Europe/Kiev',
    currency: 'Hryvnia',
    languageCodes: 'uk,ru-UA,rom,pl,hu',
  },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
    isoNumeric: '784',
    phoneCode: '971',
    continent: 'Asia',
    capital: 'Abu Dhabi',
    timeZone: 'Asia/Dubai',
    currency: 'Dirham',
    languageCodes: 'ar-AE,fa,en,hi,ur',
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    isoNumeric: '826',
    phoneCode: '44',
    continent: 'Europe',
    capital: 'London',
    timeZone: 'Europe/London',
    currency: 'Pound',
    languageCodes: 'en-GB,cy-GB,gd',
  },
  {
    name: 'United States',
    iso2: 'US',
    iso3: 'USA',
    isoNumeric: '840',
    phoneCode: '1',
    continent: 'North America',
    capital: 'Washington',
    timeZone: 'America/New_York',
    currency: 'Dollar',
    languageCodes: 'en-US,es-US,haw,fr',
  },
  {
    name: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    isoNumeric: '858',
    phoneCode: '598',
    continent: 'South America',
    capital: 'Montevideo',
    timeZone: 'America/Montevideo',
    currency: 'Peso',
    languageCodes: 'es-UY',
  },
  {
    name: 'Uzbekistan',
    iso2: 'UZ',
    iso3: 'UZB',
    isoNumeric: '860',
    phoneCode: '998',
    continent: 'Asia',
    capital: 'Tashkent',
    timeZone: 'Asia/Tashkent',
    currency: 'Som',
    languageCodes: 'uz,ru,tg',
  },
  {
    name: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
    isoNumeric: '548',
    phoneCode: '678',
    continent: 'Oceania',
    capital: 'Port Vila',
    timeZone: 'Pacific/Efate',
    currency: 'Vatu',
    languageCodes: 'bi,en-VU,fr-VU',
  },
  {
    name: 'Vatican',
    iso2: 'VA',
    iso3: 'VAT',
    isoNumeric: '336',
    phoneCode: '379',
    continent: 'Europe',
    capital: 'Vatican City',
    timeZone: 'Europe/Rome',
    currency: 'Euro',
    languageCodes: 'la,it,fr',
  },
  {
    name: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    isoNumeric: '862',
    phoneCode: '58',
    continent: 'South America',
    capital: 'Caracas',
    timeZone: 'America/Caracas',
    currency: 'Bolivar',
    languageCodes: 'es-VE',
  },
  {
    name: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
    isoNumeric: '704',
    phoneCode: '84',
    continent: 'Asia',
    capital: 'Hanoi',
    timeZone: 'Asia/Ho_Chi_Minh',
    currency: 'Dong',
    languageCodes: 'vi,en,fr,zh,km',
  },
  {
    name: 'Wallis and Futuna',
    iso2: 'WF',
    iso3: 'WLF',
    isoNumeric: '876',
    phoneCode: '681',
    continent: 'Oceania',
    capital: 'Mata Utu',
    timeZone: 'Pacific/Wallis',
    currency: 'Franc',
    languageCodes: 'wls,fud,fr-WF',
  },
  {
    name: 'Western Sahara',
    iso2: 'EH',
    iso3: 'ESH',
    isoNumeric: '732',
    phoneCode: '212',
    continent: 'Africa',
    capital: 'El-Aaiun',
    timeZone: 'Africa/El_Aaiun',
    currency: 'Dirham',
    languageCodes: 'ar,mey',
  },
  {
    name: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    isoNumeric: '887',
    phoneCode: '967',
    continent: 'Asia',
    capital: 'Sanaa',
    timeZone: 'Asia/Aden',
    currency: 'Rial',
    languageCodes: 'ar-YE',
  },
  {
    name: 'Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
    isoNumeric: '894',
    phoneCode: '260',
    continent: 'Africa',
    capital: 'Lusaka',
    timeZone: 'Africa/Maputo',
    currency: 'Kwacha',
    languageCodes: 'en-ZM,bem,loz,lun,lue,ny,toi',
  },
  {
    name: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
    isoNumeric: '716',
    phoneCode: '263',
    continent: 'Africa',
    capital: 'Harare',
    timeZone: 'Africa/Maputo',
    currency: 'Dollar',
    languageCodes: 'en-ZW,sn,nr,nd',
  },
];

faker.seed(1111111);

export const countrySeed = countries.map((country) => ({
  ...country,
  id: faker.string.uuid(),
}));
