name: 'Artifacts cleanup'
on:
  schedule:
    - cron: '0 */6 * * *' # every night at 4 am UTC, new rule: runs every six hours...

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
